modLoader = "javafml"
loaderVersion = "[36,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "yuushya"
version = "${mod_version}"
displayName = "${mod_name}"
logoFile = "pack.png"
displayURL = "${mod_homepage}"
credits = "${mod_credits}"
authors = "${mod_authors}"
description = '''
    ${mod_description}
    '''
#logoFile = ""

[[dependencies.yuushya]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.yuushya]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.5,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.yuushya]]
modId = "architectury"
mandatory = true
versionRange = "[1.32.67,)"
ordering = "AFTER"
side = "BOTH"